### ISSUE TITLE
idea: set tech node = start on a part that is hidden in tech tree when in science building

### ISSUE THREAD

**Issue by solarsootysmudge** [linuxgurugamer/JanitorsCloset#11]
On 11/23/2016 at 0:31 AM, nobodyhasthis2 said:

> @linuxgurugamer is possible to set tech node = start on a part that is hidden? 
> 
> The logic goes that this would also remove it from the normal tech tree position into start node. Since this is already unlocked at the start of the game, people don't tend look inside it. This means that as the game unfolds a part that part is hidden in the VAB can no longer be found on a later node of the tech tree and does not clutter it up. it also is not available for purchase later on if unlock costs are being used. Any thought on this?

Not really, that's outside the scope of this mod.

**It's an idea, please open an issue on Github, I might do it later**

**Comment by linuxgurugamer** [comment]
I still don't understand.  And frankly, I can see this causing issues by having hidden parts which haven't yet been unlocked, and all of a sudden these parts are now available in the initial tech node
