### ISSUE TITLE
Exception on loading to main menu

### ISSUE THREAD

**Issue by eberkain** [linuxgurugamer/JanitorsCloset#13]
I get this when loading the game with the mod active, don't think its hurting anything because the mod seems to work fine, but should probably be fixed.  

> [LOG 15:19:29.543] [AddonLoader]: Instantiating addon 'JanitorsClosetLoader' from assembly 'JanitorsCloset'
[EXC 15:19:29.551] NullReferenceException: Object reference not set to an instance of an object
	JanitorsCloset.Log.Info (System.String msg)
	JanitorsCloset.JanitorsClosetLoader.Awake ()
	UnityEngine.GameObject:AddComponent(Type)
	AddonLoader:StartAddon(LoadedAssembly, Type, KSPAddon, Startup)
	AddonLoader:StartAddons(Startup)
	<LoadObjects>c__Iterator4A:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	<CreateDatabase>c__Iterator49:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	GameDatabase:StartLoad()
	<LoadSystems>c__Iterator5D:MoveNext()
	UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
	LoadingScreen:Start()

**Comment by linuxgurugamer** [comment]
It's a single exception due to a value not being initialized in the log code.  willbe fixed in next release

**Comment by linuxgurugamer** [comment]
Should be fixed, please report if it happens again
