### ISSUE TITLE
Feature Request: Have Title of Part Visible in Prune List

### ISSUE THREAD

**Issue by pap1723** [linuxgurugamer/JanitorsCloset#17]
Often times I will hide a part using Janitors Closet and then later in my playthrough realize that I need it. In order to get it, I have to unhide all parts.

This request is to show the "title =" in the pruned list so I can find the individual part I would like to un-hide.

**Comment by linuxgurugamer** [comment]
When you say hide, are these permapruned, or just hidden?

**Comment by linuxgurugamer** [comment]
I think you are getting two different things mixed up.

When showing blocked parts, it's already showing the title and where it's been blocked from
Sounds like you are talking about the Mod Filter, and that is intended to hide/show entire mods.

Please clarify

**Comment by pap1723** [comment]
Hey @linuxgurugamer I am not home so I cannot provide any images or a log, so let me describe what I am saying...

When I ALT-click a part, and select hide in VAB. When I then click on the Janitor's Closet icon to view the list of blocked parts, no name shows up. There is a long list of parts, but the names of the parts are not displayed.

**Comment by linuxgurugamer** [comment]
Ok, I don't understand, because I do see a the names.
Please send me an image when you can so I can see what you are talking about.
Thanks

**Comment by linuxgurugamer** [comment]
See this post, is this what you are talking about:  http://forum.kerbalspaceprogram.com/index.php?/topic/147463-12-end-your-parts-list-nightmare-introducing-the-janitors-closet/&do=findComment&comment=3043939

**Comment by pap1723** [comment]
That is what I am trying to describe.

**Comment by linuxgurugamer** [comment]
ok, I'll get it fixed.  Wasn't aware of it until now
Thanks

**Comment by linuxgurugamer** [comment]
Fixed in 0.2.18
