### ISSUE TITLE
Feature Request: Show mod name next to part

### ISSUE THREAD

**Issue by nulano** [linuxgurugamer/JanitorsCloset#19]
Being able to filter parts by mods is awesome, but it would be nice to have the reverse available too: Which mod supplies this or that part?

KSP Forum discussion: http://forum.kerbalspaceprogram.com/index.php?/topic/161213-mod-name-in-part-description/

**Comment by linuxgurugamer** [comment]
Where are you looking to see that, in the part list?

**Comment by nulano** [comment]
Yeah, I'd like to see the mod name next to the parts in the VAB when I hover over them in the part list.

(Bonus points for also adding an option to see the mod when hovering over placed parts, perhaps like KER shows cost and mass of placed parts.)

**Comment by linuxgurugamer** [comment]
See newest release, but not yet over placed parts
