### ISSUE TITLE
Intermittently icons in folder/hidden dupped on App Launcher or disappear from hidden

### ISSUE THREAD

**Issue by Jacke4913** [linuxgurugamer/JanitorsCloset#22]
I've placed the icon for FMRS in a folder.  However, rarely (1 in 5 or less) going to launch I see FMRS is still on the App Launcher as well as in the folder.  Logs and JanitorsCloset.cfg in 7zip linked including when it happened once.

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170828a-JanitorsCloset-FMRS-dup-icons.screenshot_2017-08-28--00-14-06a.png

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170828a-JanitorsCloset-FMRS-dup-icons.7z

**Comment by Jacke4913** [comment]
I've encountered a worse example.  I'd set up a number of hidden icons and others put in a folder on launch from the SPH.  On going to launch from the VAB, I found all the icons I'd hidden also on the App Launcher.

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170828c-JanitorsCloset-many-dup-icons.screenshot_2017-08-28--03-22-19a.png

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170828c-JanitorsCloset-many-dup-icons.7z

**Comment by Jacke4913** [comment]
Trying to fix the JC icons, I removed the ones hidden, then tried to hide them again.  They could be removed from the hidden list on the JC icon but when trying to hide them again, the buttons on the popup menu from the alt-right-click wouldn't work.  Logs and JanitorsCloset.cfg in 7zip linked below.

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170828d-JanitorsCloset-many-dup-icons.7z

**Comment by Jacke4913** [comment]
I tried resetting JanitorsCloset.cfg back to its default and setting it up again.  Could go to flight via the VAB and both hide icons and put them in a folder.  Reverted to VAB and found I couldn't hide an icon in the VAB.  Launched to flight again and found folder okay but no icons hidden and those hidden icons not present in the App Launcher.  As well, couldn't hide any further icons.  Logs and JanitorCloset.cfg in 7zip.

**Comment by Jacke4913** [comment]
I swapped around a few mods, including adding scatterer back in.  Also started a new savegame.  Was recreating hiding away icons when I encountered problems.  I tried hiding the green wireframe globe icon (see screenshot) and it didn't apparently work.  Tried putting it into a folder and that apparently didn't work.  Reverted to the VAB and went to launch.  That icon was in the folder.  And the hidden icons had disappeared.  Apparently more sensitive to a memory threshold than I thought.  Will have to cut out more mods, at least scatterer.

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170829a-JanitorsCloset-hide-faults.screenshot_2017-08-29--17-12-34a.png

http://www.cuug.ab.ca/jacke/KSP/v1.3.0/_logs/20170829a-JanitorsCloset-hide-faults.7z

**Comment by Jacke4913** [comment]
Note: green wireframe globe is from Collide-O-Scope mod.  It is working.  Green is enabled and then right-clicking parts allows turning on wireframes of colliders.

**Comment by cartersm** [comment]
I'm encountering the same issue, as posted in the forum topic for JC: https://forum.kerbalspaceprogram.com/index.php?/topic/147463-130-end-your-parts-list-nightmare-introducing-the-janitors-closet/&do=findComment&comment=3133010

**Comment by tofof** [comment]
Issue persists in JC 0.3.5.1, on KSP 1.7.3

**Comment by talchas** [comment]
Once you have something hidden/foldered in one scene and then later hide-everywhere it later, the whole mod gets wedged and is probably causing some of these issues. If you see an ArgumentException with JanitorsCloset in the backtrace thhat's probably the issue.

The easy code fix is to replace LINQ Concat+ToDictionary [here](https://github.com/linuxgurugamer/JanitorsCloset/blob/master/JanitorsCloset/JanitorsToolbar.cs#L371) with a simple foreach loop + hiddenButtons[key]=value, and again in addToHiddenBlockList (and while the similar saveload stuff shouldn't trigger once everything else is fixed, it probably could use it too). AFAICT LINQ has no efficient ToDictionary variant that does anything useful on duplicates.

**Comment by linuxgurugamer** [comment]
Thank you, I'll look at it later today

**Comment by linuxgurugamer** [comment]
Ok, so I've done the first at line 371, but in addToHiddenBlockList(), there isn't any linq that I can see.

**Comment by talchas** [comment]
Oh, sorry, that one is Add, I was thinking of "throws exception on duplicates in general" when I said it was the same.

**Comment by linuxgurugamer** [comment]
Just released, I'd appreciate if you could take a look

**Comment by talchas** [comment]
Yeah, that's basically what I did locally; I generally used `foo[x]=y;` instead, which has the later value take precedence instead, but that's mostly irrelevant.
