### ISSUE TITLE
Add "ALL" option to mod filter, not just "ANY"

### ISSUE THREAD

**Issue by Xetaxheb** [linuxgurugamer/JanitorsCloset#28]
My only use-case for this mod would be hiding all parts that have 'Intake Air' as a storage/requirement/generator, but there's [seemingly] no way to do that without: 
1. Alt+click hiding each individual part which is very time consuming
2. Unchecking multiple mod-filter options until they disappear which inadvertently catches parts I'd rather were shown

Currently this functions as a "show any parts that have this flag", I'm asking for a "hide any parts that have this flag" feature.

Could be as simple as right clicking the mod-filter buttons to turn them red (instead of green or off) or having a 2nd button on each entry.

**Comment by linuxgurugamer** [comment]
Ok, if I understand you correctly, you want to be able to hide (instead of show) parts which match.
Good idea, I'll see if I can do it

**Comment by linuxgurugamer** [comment]
Please explain to my why you can't get the same result of excluding anything with a specific resource by simply selecting all resources except the one you want to exclude.

**Comment by linuxgurugamer** [comment]
Never mind, I had to think about it.  I'm working on this now

**Comment by Xetaxheb** [comment]
Yes, that second comment is what I would like to be able to do, aka a blacklist for certain part functions/features :)

**Comment by linuxgurugamer** [comment]
Well, right now I've added an exclusion to the resources, so you will be able to, for example, exclude any part that uses IntakeAir (ie:  jets, SABREs, etc).

Currently there is not a filter in place regarding part functionality.  

It doesn't make any sense to add an exclusion to the mod names, and essentially the same goes for the sizes;  all you need to do for those is uncheck the associated toggle.

While possible to add filters based on part functionality, it's actually a lot of additional work which would be needed, and would increase the overhead in the editor.  The only way to do that is to look for the part modules in each part

**Comment by linuxgurugamer** [comment]
Just an fyi, I have added a partmodule filter

**Comment by Xetaxheb** [comment]
Yeah resources is really all that's needed, I meant that and not "functions", sorry. I can't think of a good situation that would need to blacklist "functions" either (let alone warrant the overhead), and as you said the other capabilities exist via unchecking other toggles.
Thanks for the fast work and all the maintenance you do, you really are a massive contributor to this game and community.

**Comment by linuxgurugamer** [comment]
Just released the update
