### ISSUE TITLE
NullReference when hovering over BG container icons

### ISSUE THREAD

**Issue by lampeh** [linuxgurugamer/JanitorsCloset#30]
A null reference exception happens in ModFilterWindow.FindPartMod() when hovering over an empty slot in the Breaking Ground container inventory. The "part" argument passed on from JanitorsCloset.IconHover() is null.

![bghover](https://user-images.githubusercontent.com/758097/91099427-9427ab80-e663-11ea-93cb-db24a6dddcd0.jpg)

There are different ways to fix this. A check in IconHover works for me:
```
         private void IconHover(EditorPartIcon icon, bool hover)
         {
             Log.Info("IconHover,  ExtendedInput.GetKey(GameSettings.MODIFIER_KEY.primary): " + ExtendedInput.GetKey(GameSettings.MODIFIER_KEY.primary).ToString());
-            if (HighLogic.CurrentGame.Parameters.CustomParams<JanitorsClosetSettings>().showMod ||
-                ExtendedInput.GetKey(GameSettings.MODIFIER_KEY.primary) || ExtendedInput.GetKey(GameSettings.MODIFIER_KEY.secondary))
+            if (icon.partInfo != null && (HighLogic.CurrentGame.Parameters.CustomParams<JanitorsClosetSettings>().showMod ||
+                ExtendedInput.GetKey(GameSettings.MODIFIER_KEY.primary) || ExtendedInput.GetKey(GameSettings.MODIFIER_KEY.secondary)))
```

[KSP.log](https://github.com/linuxgurugamer/JanitorsCloset/files/5120347/KSP.log)

[hovernull.diff.txt](https://github.com/linuxgurugamer/JanitorsCloset/files/5120352/hovernull.diff.txt)

**Comment by linuxgurugamer** [comment]
I think this is fixed, please reopen if it isn't
