### ISSUE TITLE
[1.11.2]KSP stucks at loading expansions if janitors closet is installed

### ISSUE THREAD

**Issue by tonimark** [linuxgurugamer/JanitorsCloset#31]
I found a bug where if the latest versions of janitors closet is installed the KSP will stuck at "loading expansion..." phase without loading any other stuff
mod list:
[mod list.txt](https://github.com/linuxgurugamer/JanitorsCloset/files/6217157/mod.list.txt)
[debug.log](https://github.com/linuxgurugamer/JanitorsCloset/files/6217159/debug.log)
[KSP.log](https://github.com/linuxgurugamer/JanitorsCloset/files/6217160/KSP.log)
[Player.log](https://github.com/linuxgurugamer/JanitorsCloset/files/6217162/Player.log)

additional notes: the  module manager patcher reported the gamedata\JanitorsCloset\Plugins\JanitorsCloset.dll 
incompatible with the ksp 1.11.2

**Comment by linuxgurugamer** [comment]
you have Kerbalism installed:

Exception handling event OnPartLoaderLoaded in class Loader:System.NullReferenceException: Object reference not set to an instance of an object
  at KERBALISM.Loader.SaveHabitatData () [0x00006] in <c01b58fa9151425eac28bc1f9ddf5307>:0 
  at EventVoid.Fire () [0x00127] in <06f13185617646e5bc801baeab53ab75>:0

**Comment by tonimark** [comment]
i have to say when i only install janitors closet it gets stuck when I uninstall it , it works normally
