### ISSUE TITLE
You seem to have missed a spot.....

### ISSUE THREAD

**Issue by Slelsul** [linuxgurugamer/JanitorsCloset#32]
Honestly I know you have your work cut out for you but it would seem as though you are the only one that supports this mod. It also seems as though you forgot or just generally neglected KSP v1.10.0 and the like. I could just update to latest but my mod list and own reasons say otherwise. 

I came up on this mod by chance and I would like to have it if only it were compatible. I apologize if I seem a bit rude but I just generally have this extreme irritation with half measures. I look for ages and found that as much as this mod is compatible with many other version my version seems to be that only one not supported and that is very upsetting after hours or days of fruitless work to be honest.

I won't ask you to understand. It is just my OCD and perfectionism that is to blame for my level of irritation. Or it could be that I am just realizing I am screwed because of this. I just ask that you at the very least consider supporting every version including my 1.10.0. It is too insanely difficult to get any mod to work anymore with any game. Modders have forsaken us peasants.

Edited for spelling

**Comment by linuxgurugamer** [comment]
it is compatible, just tell CKAN to allow the compatibility.

I maintain >240 mods, can't go through the entire list every time an update comes out.  That's why CKAN added the compatiblity section
