### ISSUE TITLE
Feature request: option to generate restockblacklist

### ISSUE THREAD

**Issue by Vladimir-csp** [linuxgurugamer/JanitorsCloset#33]
ReStock has a blacklist feature that prevents loading assets listed in `*.restockblacklist` files.
JanitorsCloset could leverage that by maintaing it's own list, without renaming anything.

**Comment by linuxgurugamer** [comment]
I fail to understand what this will do.  JC already has it's own blacklist, used to hide things.  If the asset isn't loaded, JC doesn't know about it

**Comment by Vladimir-csp** [comment]
The idea is to use ReStock as a "backend" for asset loading prevention, instead of renaming files. It is non-invasive and easy to manage.

**Comment by linuxgurugamer** [comment]
But, if assets aren't loaded, this mod doesn't know about it.  Restock works before this does, there is no need to do anything, from what I can tell.

Besides, sometimes you want to hide assets without deleting them, because they may be used by other parts

**Comment by Vladimir-csp** [comment]
ReStock reads all `*.restockblacklist` in GameData, so JC can maintain it's own `jc.restockblacklist` file in GameData and know about blacklisted parts just by reading it, so it would be possible to present the list in-game for user to "undelete" stuff.

**Comment by linuxgurugamer** [comment]
Sorry, two different functionalities.  Restock's blacklist is there to allow it to work.  JC works in a totally different manner.
This is unnecessary work for me, sorry
