### ISSUE TITLE
Feature request: replace the "filter by manufacturer" tab with instead filtering by mod.

### ISSUE THREAD

**Issue by truehunterethan** [linuxgurugamer/JanitorsCloset#36]
where each mod will have its own folder thingy and the parts of each mod will be stored in there. no one uses the filter by manufacturer anyways.

**Comment by linuxgurugamer** [comment]
Filtering by mod is already there (I use it all the time), and some people do filter by manufacturer

**Comment by truehunterethan** [comment]
do you filter by mod by just excluding all other mods on the parts list?
