### ISSUE TITLE
[1.12.2]janitors closet ddl is not compatible with the latest versions of KSP

### ISSUE THREAD

**Issue by tonimark** [linuxgurugamer/JanitorsCloset#37]
[KSP.log](https://github.com/linuxgurugamer/JanitorsCloset/files/7316256/KSP.log)
[Player.log](https://github.com/linuxgurugamer/JanitorsCloset/files/7316263/Player.log)
![problem](https://user-images.githubusercontent.com/17166550/136671605-8ff0b486-b282-4831-8049-72a5ab9a95aa.png)

**Comment by linuxgurugamer** [comment]
It was, and is
