### ISSUE TITLE
Reloading database causes multiple mouse clicks in the editor

### ISSUE THREAD

**Issue by Shadlock0133** [linuxgurugamer/JanitorsCloset#38]
While making a mod, i've noticed that reloading the database (in the cheat menu) with JanitorsCloset 0.3.7.9 will result in a bug in the editor, where multiple mouse clicks events are send with one press, one extra for each reload (so no reloads = 1 click (as expected), one reload = 2 clicks). This, for example, makes it impossible to pick up parts on even number of clicks, as they're immediately deleted.

Restarting the game fixes it.

I've been using this mods (through ckan):
[janitor bug.txt](https://github.com/linuxgurugamer/JanitorsCloset/files/11147103/janitor.bug.txt)
and removing "The Janitor's Closet" (together with "SpaceTux Library") also removes the bug, so i'm guessing this is what's causing it.

**Comment by linuxgurugamer** [comment]
Reloading the database is not supported.  It's a hack, intended for mostly developing mods. 

If you do that, no one (including myself) is going to support that

Sorry


LGG
