### ISSUE TITLE
Not working under ver 1.12.5

### ISSUE THREAD

**Issue by Linrox** [linuxgurugamer/JanitorsCloset#40]
Maybe i missed something during the install. Copied the gamedata into KSP.
Tried this useful mod in KSP 1.12.5.3190, but can't see the icon anywhere, alt r-Click on a part does not show hide option.

Tried both the Github version JanitorsCloset-1.12.0-0.3.8 and the space dock version The_Janitors_Closet-0.3.8

**Comment by linuxgurugamer** [comment]
You probably didn't install the dependencies.  

My mods all work best when installed using CKAN, it installs all necessary dependencies and avoids conflicts.
If you still have problems, post on the forum and include a log file.  This isn't a bug
