### ISSUE TITLE
Feature Request - Filter Presets

### ISSUE THREAD

**Issue by JebsSY** [linuxgurugamer/JanitorsCloset#6]
I would have a feature suggestion. Could the mod-filter-window get some preset buttons? Maybe 1,2,3,4,5. With the possibility to save a mod selection to that button. Save could be something simple CTRL + Button1, maybe. And Button1 just restores the selected mods.

For what it would be useful? I have plenty part mods, for example 10, but regarding the loading times I consider, that maybe 1,2,3 out of the part mods could get removed later. However, when loading the savegame then, the ships with those parts get deleted. Cause of that I build mission dependent. For a short mission, I use parts from all mods. For a long and maybe important mission, for example a scansat or a ISRU on a far planet, I only use the stock parts and parts from mods that stay100% in my installation.

With such preset button row one could easily switch between some mission / part profile list. :) I almost would say these buttons could even be more/faster accessible then in the part filter menu, but if they are there that would be fine enough. Just the case "new mod adds new parts" must be considered, but when not in the "not selected" list then just show it. So maybe the saved preset should save the deselected mods. 

Just as an idea. Don't know if it's possibe / how much work it is.

**Comment by linuxgurugamer** [comment]
Need clarification.  You are aware that the modlist filter merely hides parts, it doesn't remove them?
Parts which aren't permapruned are still loaded, just not visible.
