### ISSUE TITLE
Feature Request - Save filter list

### ISSUE THREAD

**Issue by JebsSY** [linuxgurugamer/JanitorsCloset#9]
It would be really handy if JC could save the deselected mods from the filter list.
With this feature you can have special big count part mods installed, but only enable them on demand. They still use memory but at least they don't clutter the VAB.
So maybe it's possible to store the list of deselected mods and deselect them again when entering the VAB.
That way new added mods are also enabled by default.

**Comment by linuxgurugamer** [comment]
done
